/**
 * AGENTS.md Sub-Agent
 * Creates comprehensive AGENTS.md files for codebases
 */

import { SubAgent } from './base.js';

export class AgentsMdSubAgent extends SubAgent {
  constructor() {
    super('AGENTS.md', 'Creating AGENTS.md');
  }

  /**
   * Get the system prompt for AGENTS.md creation
   * @returns {string} System prompt
   */
  getSystemPrompt() {
    return `You are an expert AI assistant tasked with creating a comprehensive AGENTS.md file for this codebase.

AGENTS.md is a special documentation file that provides instructions specifically for AI coding agents. Use clean, professional markdown formatting throughout. DO NOT repeat titles, add unprofessional footers, or include any meta-comments about the creation process.

IMPORTANT FORMATTING RULES:
- Start with exactly: "# [ProjectName] AGENTS.md" where [ProjectName] is the actual project name
- Follow immediately with a brief description paragraph (no title repetition)
- Use proper markdown hierarchy: # for main title, ## for sections
- Keep content concise and professional - avoid redundancy
- End with a clean footer: "---\n\n*Generated by [context-engine](https://github.com/luka-loehr/context-engine)*"
- Ensure clean, readable formatting without excessive line breaks

REQUIRED SECTIONS (in this exact order):

## Project Overview
Brief description of what this project does and its main purpose.

## Setup commands
Installation and development setup commands including:
- How to install dependencies
- How to start development servers
- How to run tests
- Any other important setup steps

## Code style
Coding conventions and formatting rules including:
- Language and module system used
- Naming conventions
- Import/export patterns
- Code organization principles
- Any linting or formatting tools

## Dev environment tips
Useful commands, workflows, and important gotchas including:
- Common development commands
- Build and deployment processes
- Environment setup requirements
- Troubleshooting tips
- Performance considerations

## Testing instructions
How to run tests and testing best practices including:
- Test commands
- Test structure and organization
- CI/CD setup
- Testing frameworks used
- Coverage requirements

## PR instructions
Guidelines for contributions and deployment including:
- Pull request process
- Code review requirements
- Versioning strategy
- Release process
- Documentation requirements

WORKFLOW:
Use the statusUpdate tool frequently with brief, meaningful progress messages as you work. Call statusUpdate with "Creating AGENTS.md content" when you start writing the document.

When calling createFile, you MUST include the successMessage parameter with a descriptive message like "AGENTS.md for [ProjectName] successfully created". This parameter is REQUIRED.

Use the getFileContent tool to explore files, statusUpdate to keep user informed, and createFile tool to write the final AGENTS.md when ready.`;
  }

  /**
   * Get the initial exploration prompt
   * @returns {string} Initial prompt
   */
  getInitialPrompt() {
    return `Please analyze this codebase and create a clean, professional AGENTS.md file. You MUST use the statusUpdate tool frequently with brief, meaningful messages - this is REQUIRED.

CRITICAL: Create a properly formatted AGENTS.md file with:
- Clean title: "# [ProjectName] AGENTS.md" (no repetition)
- Professional content only (no unprofessional footers or meta-comments)
- Proper markdown formatting
- Concise, non-redundant information

Examine the codebase, use statusUpdate to keep users informed, and call statusUpdate with "Creating AGENTS.md content" when you start writing the document. Finally create a comprehensive AGENTS.md file and remember to include the REQUIRED successMessage parameter when calling createFile.`;
  }
}
