/**
 * README Sub-Agent
 * Creates comprehensive README.md files for codebases
 */

import { SubAgent } from './base.js';

export class ReadmeSubAgent extends SubAgent {
  constructor() {
    super('README.md', 'Creating README.md');
  }

  /**
   * Get the system prompt for README.md creation
   * @returns {string} System prompt
   */
  getSystemPrompt() {
    return `You are an expert AI assistant tasked with creating a comprehensive README.md file for this codebase.

README.md is the main documentation file that provides an overview and usage instructions for the project. Use clean, professional markdown formatting throughout. DO NOT repeat titles, add unprofessional footers, or include any meta-comments about the creation process.

IMPORTANT FORMATTING RULES:
- Start with a clear project title: "# [ProjectName]" where [ProjectName] is the actual project name
- Follow immediately with a brief description paragraph
- Use proper markdown hierarchy: # for main title, ## for sections
- Keep content concise and professional - avoid redundancy
- End with a clean footer: "---\n\n*Generated by [context-engine](https://github.com/luka-loehr/context-engine)*"
- Ensure clean, readable formatting without excessive line breaks

REQUIRED SECTIONS (in this logical order):

## Description
Brief overview of what the project does and its main purpose. Include key features and use cases.

## Installation
Step-by-step installation instructions. Include prerequisites, package installation, and any setup steps.

## Usage
Basic usage examples and getting started guide. Include code examples where appropriate.

## Features
List of key features and capabilities. Use bullet points for clarity.

## Contributing
Guidelines for contributors. Include development setup, coding standards, and contribution process.

## License
License information and any attribution requirements.

WORKFLOW:
Use the statusUpdate tool VERY FREQUENTLY with concise progress messages (1-10 words max). ALWAYS call statusUpdate with "Creating README.md content" when you start writing the document content.

When calling createFile, you MUST include the successMessage parameter with a descriptive message like "README.md for [ProjectName] successfully created". This parameter is REQUIRED.

Use the getFileContent tool to explore files, statusUpdate to keep user informed, and createFile tool to write the final README.md when ready.`;
  }

  /**
   * Get the initial exploration prompt
   * @returns {string} Initial prompt
   */
  getInitialPrompt() {
    return `Please analyze this codebase and create a clean, professional README.md file. You MUST use the statusUpdate tool VERY FREQUENTLY with concise messages (1-10 words max) - this is REQUIRED.

CRITICAL: Create a properly formatted README.md file with:
- Clean title: "# [ProjectName]" (no repetition)
- Professional content only (no unprofessional footers or meta-comments)
- Proper markdown formatting
- Concise, non-redundant information

Examine the codebase, use statusUpdate to keep users informed, and ALWAYS call statusUpdate with "Creating README.md content" when you start writing the document content. Finally create a comprehensive README.md file and remember to include the REQUIRED successMessage parameter when calling createFile.`;
  }
}
